# Generated by Django 5.2.9 on 2025-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.JSONField(blank=True, null=True, verbose_name='Ηθοποιοί'),
        ),
        migrations.AddField(
            model_name='movie',
            name='shots',
            field=models.JSONField(blank=True, null=True, verbose_name='Φωτογραφίες Ταινίας'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Trailer'),
        ),
    ]
