# Generated by Django 5.2.10 on 2026-01-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_actors_movie_shots_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(blank=True, help_text='Οι αριθμοί των θέσεων που κρατήθηκαν (π.χ. A1, A2, B5)', max_length=500, verbose_name='Αριθμοί Θέσεων'),
        ),
    ]
