# Generated by Django 6.0.2 on 2026-02-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_seatlock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatlock',
            unique_together={('screening', 'seat_number')},
        ),
    ]
