# Generated by Django 6.0.2 on 2026-02-26 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_moviehall_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviehall',
            name='left_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Αριστερού Τμήματος'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='middle_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Μεσαίου Τμήματος'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='right_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Δεξιού Τμήματος'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Συνολική Χωρητικότητα (Υπολογίζεται αυτόματα)'),
        ),
    ]
