# Generated by Django 6.0.2 on 2026-02-26 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_moviehall_left_section_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviehall',
            name='balcony_left_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Αριστερού Τμήματος (Εξώστης)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='balcony_middle_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Μεσαίου Τμήματος (Εξώστης)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='balcony_right_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Δεξιού Τμήματος (Εξώστης)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='left_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Αριστερού Τμήματος (Πλατεία)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='middle_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Μεσαίου Τμήματος (Πλατεία)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='right_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Χωρητικότητα Δεξιού Τμήματος (Πλατεία)'),
        ),
    ]
