# Generated by Django 6.0.2 on 2026-02-26 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_moviehall_balcony_left_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviehall',
            name='balcony_left_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = αυτόματος υπολογισμός', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις/Σειρά Αριστερά (Εξώστης)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='balcony_middle_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = αυτόματος υπολογισμός', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις/Σειρά Μεσαία (Εξώστης)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='balcony_right_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = αυτόματος υπολογισμός', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις/Σειρά Δεξιά (Εξώστης)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='left_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = αυτόματος υπολογισμός', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις/Σειρά Αριστερά (Πλατεία)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='middle_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = αυτόματος υπολογισμός', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις/Σειρά Μεσαία (Πλατεία)'),
        ),
        migrations.AddField(
            model_name='moviehall',
            name='right_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = αυτόματος υπολογισμός', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θέσεις/Σειρά Δεξιά (Πλατεία)'),
        ),
    ]
