# Generated by Django 5.2.7 on 2025-10-13 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Διάρκεια (λεπτά)')),
                ('genre', models.CharField(max_length=100, verbose_name='Είδος')),
                ('director', models.CharField(max_length=200, verbose_name='Σκηνοθέτης')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Έτος Κυκλοφορίας')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Βαθμολογία')),
                ('poster_url', models.URLField(blank=True, null=True, verbose_name='URL Αφίσας')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Ταινία',
                'verbose_name_plural': 'Ταινίες',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Αριθμός Αίθουσας')),
                ('start_time', models.DateTimeField(verbose_name='Ώρα Έναρξης')),
                ('end_time', models.DateTimeField(verbose_name='Ώρα Λήξης')),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Διαθέσιμες Θέσεις')),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Συνολικές Θέσεις')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Εισιτηρίου')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.movie', verbose_name='Ταινία')),
            ],
            options={
                'verbose_name': 'Προβολή',
                'verbose_name_plural': 'Προβολές',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Όνομα Πελάτη')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email Πελάτη')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Πελάτη')),
                ('seats_booked', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Αριθμός Θέσεων')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Συνολική Τιμή')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Κράτησης')),
                ('status', models.CharField(choices=[('confirmed', 'Επιβεβαιωμένη'), ('cancelled', 'Ακυρωμένη'), ('pending', 'Εκκρεμής')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.screening', verbose_name='Προβολή')),
            ],
            options={
                'verbose_name': 'Κράτηση',
                'verbose_name_plural': 'Κρατήσεις',
                'ordering': ['-booking_date'],
            },
        ),
    ]
