# Generated by Django 5.2.9 on 2025-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('now_playing', 'Now Playing')], default='upcoming', max_length=20, verbose_name='Status'),
        ),
    ]
