# Generated by Django 4.2.28 on 2026-02-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_booking_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Αριθμός Θέσης')),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='cinema.screening', verbose_name='Προβολή')),
            ],
            options={
                'verbose_name': 'Προσωρινή Δέσμευση',
                'verbose_name_plural': 'Προσωρινές Δεσμεύσεις',
            },
        ),
    ]
