# Generated by Django 6.0.2 on 2026-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_seatlock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviehall',
            name='layout',
            field=models.JSONField(blank=True, help_text='JSON με τη διάταξη των θέσεων. Αν δεν δοθεί, δημιουργείται αυτόματα.', null=True, verbose_name='Διάταξη Αίθουσας'),
        ),
    ]
