# Generated by Django 6.0.2 on 2026-02-26 21:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_moviehall_balcony_left_seats_per_row_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='moviehall',
            options={'ordering': ['name'], 'verbose_name': 'Cinema Hall', 'verbose_name_plural': 'Cinema Halls'},
        ),
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['start_time'], 'verbose_name': 'Screening', 'verbose_name_plural': 'Screenings'},
        ),
        migrations.AlterModelOptions(
            name='seatlock',
            options={'verbose_name': 'Seat Lock', 'verbose_name_plural': 'Seat Locks'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.screening', verbose_name='Screening'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(blank=True, help_text='Comma-separated seat identifiers, e.g. A1, A2, B5', max_length=500, verbose_name='Seat Numbers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Seats'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who made the booking (optional for guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.JSONField(blank=True, null=True, verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=200, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (min)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='Poster URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Release Year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='shots',
            field=models.JSONField(blank=True, null=True, verbose_name='Scene Shots'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Trailer URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='balcony_left_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Left Section Capacity (Balcony)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='balcony_left_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = auto-calculate', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seats/Row Left (Balcony)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='balcony_middle_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Middle Section Capacity (Balcony)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='balcony_middle_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = auto-calculate', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seats/Row Middle (Balcony)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='balcony_right_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Right Section Capacity (Balcony)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='balcony_right_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = auto-calculate', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seats/Row Right (Balcony)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Capacity (auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='layout',
            field=models.JSONField(blank=True, help_text='JSON seat layout. Auto-generated if blank.', null=True, verbose_name='Hall Layout'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='left_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = auto-calculate', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seats/Row Left (Main)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='left_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Left Section Capacity (Main)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='middle_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = auto-calculate', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seats/Row Middle (Main)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='middle_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Middle Section Capacity (Main)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Hall Name'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='right_seats_per_row',
            field=models.IntegerField(default=0, help_text='0 = auto-calculate', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seats/Row Right (Main)'),
        ),
        migrations.AlterField(
            model_name='moviehall',
            name='right_section_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Right Section Capacity (Main)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='available_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available Seats'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.moviehall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ticket Price'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='seatlock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='seatlock',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='cinema.screening', verbose_name='Screening'),
        ),
        migrations.AlterField(
            model_name='seatlock',
            name='seat_number',
            field=models.CharField(max_length=10, verbose_name='Seat Number'),
        ),
    ]
