# Generated by Django 6.0.2 on 2026-03-01 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_booking_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
