# Generated by Django 6.0.3 on 2026-03-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_booking_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the hall')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cinema.moviehall')),
            ],
            options={
                'verbose_name': 'Hall Photo',
                'verbose_name_plural': 'Hall Photos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
