# Generated by Django 6.0.3 on 2026-03-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_subscription'),
    ]

    operations = [
    ]
