# Generated by Django 6.0.3 on 2026-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_merge_0013_add_hall_photo_0015_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending_payment', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for this booking', max_length=255, null=True, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID for the last subscription purchase', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for recurring billing', max_length=255, null=True),
        ),
    ]
