name: Deploy to DigitalOcean

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to App Platform
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app_spec_location: digitalocean/app.yaml
